### ISSUE TITLE
Getting started documentation

### ISSUE THREAD

**Issue by kubeliv** [GayPizzaSpecifications/concrete#3]
It would be great to have some documentation, in either the README or wiki to get started with this plugin. Particularly, it should follow one or more of the sample projects provided by @azenla

**Comment by azenla** [comment]
liv is hungry

**Comment by azenla** [comment]
Cynthia Johnson

**Comment by ScrelliCopter** [comment]
![1103873746504261644](https://github.com/GayPizzaSpecifications/concrete/assets/11264000/8304b3c9-ff43-4f6a-9b6a-55c92a8c3e4c)

**Comment by azenla** [comment]
![IMG_4646](https://github.com/GayPizzaSpecifications/concrete/assets/2130849/7bb62747-dbf9-4acb-9a94-6c3f76c4750e)

**Comment by azenla** [comment]
![IMG_0025](https://github.com/GayPizzaSpecifications/concrete/assets/2130849/ef1d0510-6289-474f-80a8-e6887c316c97)

**Comment by azenla** [comment]
Announcing my imminent release of https://pullman.rip
